/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.justrudd.aoc2022.kotlin-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("dev.justrudd.aoc2022.day02.MainKt")
}
